version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: book_db
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
